

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=laliga
      - DB_PASSWORD=laliga2024
      - DB_NAME=laliga
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=laliga
      - POSTGRES_USER=laliga
      - POSTGRES_PASSWORD=laliga2024
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: